apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: open5gs
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 27017
    targetPort: 27017
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mongodb
  namespace: open5gs
subsets:
- addresses:
  - ip: 10.34.4.245  # CHANGE THIS to your MongoDB IP
  ports:
  - port: 27017