apiVersion: v1
kind: ConfigMap
metadata:
  name: pcf-config
  namespace: open5gs
data:
  pcf.yaml: |
    logger:
      file:
        path: /var/log/open5gs/pcf.log
        timestamp: true
      default:
        timestamp: true
    #  level: info   # fatal|error|warn|info(default)|debug|trace

    global:
      max:
        ue: 1024  # The number of UE can be increased depending on memory size.
    #    peer: 64

    pcf:
      sbi:
        server:
          - address: 10.10.0.13
            port: 7777
        client:
          nrf:
            - uri: http://10.10.0.10:7777
          scp:
            - uri: http://10.10.0.200:7777
      metrics:
        server:
          - address: 10.10.0.13
            port: 9090